# Generated by Django 3.2.9 on 2021-11-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='artist_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermodel',
            name='customer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
