# Generated by Django 3.2.7 on 2021-12-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artData', '0003_artistmodel_artshowmodel_buyermodel_collectormodel_rentermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('style', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('artist_id', models.IntegerField()),
                ('collector_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.IntegerField()),
                ('start_date', models.DateField()),
                ('return_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('rent_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('artist_percentage', models.IntegerField()),
                ('renter_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('invoice_num', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('artist_percentage', models.IntegerField()),
                ('buyer_id', models.IntegerField()),
            ],
        ),
    ]
