# Generated by Django 3.2.9 on 2021-12-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artData', '0004_artworkmodel_rentmodel_salemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='customer_id',
        ),
    ]
