# Generated by Django 3.2.9 on 2021-12-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artData', '0007_customermodel_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('street_num', models.IntegerField()),
                ('street_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('preferred_style', models.CharField(max_length=50)),
                ('preferred_medium', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=25)),
                ('artist_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
