# Generated by Django 3.2.9 on 2021-12-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artData', '0009_auto_20211202_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='customer_id',
        ),
    ]
