# Generated by Django 3.2.9 on 2021-12-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artData', '0010_remove_customermodel_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='query2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_cost_to_buy', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='collectormodel',
            name='collector_id',
        ),
        migrations.AddField(
            model_name='artworkmodel',
            name='type',
            field=models.CharField(default=100000, max_length=50),
            preserve_default=False,
        ),
    ]
