# Generated by Django 3.2.9 on 2021-12-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artData', '0011_auto_20211202_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectormodel',
            old_name='artist_id',
            new_name='artist_id_id',
        ),
    ]
