# Generated by Django 3.2.9 on 2021-12-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artData', '0014_remove_artworkmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id_sold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artData.artworkmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RentedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artData.artworkmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artData.artshowmodel')),
            ],
        ),
    ]
